### PR TITLE
Split checkbox demo into client-only and remote

### LINKED ISSUE #89: [Bug] Checkbox validation does not work (verified in demo app)
My model has a `bool` bound to a checkbox. It's not required, so I should be able to submit the form without checking it. But validation fails for the checkbox and I can't submit.

**I tried the demo, and it also fails.**

The demo has this:
```cs
    [BindProperty]
    public InputModel Input { get; set; } = new();

    // ...

    public class InputModel
    {
        [Remote("CheckboxRemote", "Validations", HttpMethod = "Post")]
        public bool IsChecked { get; set; }
    }
```

When trying to submit the form on the `http://localhost:5000/Demos/Checkboxes` page:
> NET renders a checkbox and a hidden input ... it is unchecked. **Unchecking it should not fail validation.**
> 
> **'IsChecked' is invalid.** This is not checked

One can easily verify this repro, just run the demo, go to that page and click submit.

I think it's a bug.

### PR DESCRIPTION
**Pull request by lonix1**
Closes #89

### CODE REVIEW

File: Controllers/Validations.cs [hunk 1]
```diff
@@ -11,9 +11,9 @@ public IActionResult CheckRemote(string id)
     }
 
     [HttpPost]
-    public IActionResult CheckboxRemote(bool isChecked)
+    public IActionResult CheckboxRemote(bool isChecked, bool isCheckedToo)
     {
-        return Ok(isChecked);
+        return Ok(isChecked == isCheckedToo);
```
Comment (dahlbyk) [inline Controllers/Validations.cs:16]: This is a more interesting demo of `[Remote]`, including [`AdditionalFields`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.remoteattributebase.additionalfields).

**Review by dahlbyk — APPROVED** [review]
I was going to leave a few suggestions (merge the models, make the validator more interesting), but went ahead and made them myself.
msedge_VlNojKHs79

Thoughts?

**Comment by haacked** [comment]
Thanks!
