### PR TITLE
Fix removing validation + Undebounce

### LINKED ISSUE #100: Disabling validation
For diagnostic and/or testing purposes we needed to disable the library once it's already loaded.

I tried this:
```js
v.remove(v.options.root)
```
And this:
```js
document.querySelectorAll('.my-form input:not([type="hidden"])').forEach(x => v.removeInput(x));
```
Both complete without error, but when I then interact with the form, and validation is expected to run, I get this console error:
```
Uncaught TypeError: i is not a function
  a http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  setTimeout handler*i http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  addInput http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  scanInputs http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  scan http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  a http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  bootstrap http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  <anonymous> http://localhost:5000/signin:355
```

Are [`remove`](https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/dist/aspnet-validation.js#L1313) and [`removeInput`](https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/dist/aspnet-validation.js#L1038) intended to be usable by callers (in which case have I made a mistake in how I'm using them)? If not, is there some other way to disable the library once it's loaded, or is that impossible (and the only option is not to run it in the first place)?

### LINKED ISSUE #108: Initial isFieldValid returns true when field is empty and uses required validator.
On calling v.isFieldValid and passing an element it appears to use the cached version even though it has not previously run.

From the code for isFieldValid I can see the validation is set up to run on the debounce timeout, which I have set to 0 on bootstrap.

This results in isFieldValid returning true even though it has not called the validator. The validator fires after the function returns and evaluates to false. There is no async code.

I'm going to work around this by using the callback.

Is it an error that the state is returned as true when it has not been through a validator? From the docs on this function it's not obvious that the return state is cached.

Would you consider an alternative (which I'll help with) if the debounce is 0, calling the validator and returning the state immediately?
That might still make the return value unreliable if debounce is not 0 though.

Basic idea of what I am doing is below;

`<input type="text" data-val="true" data-val-required="Please enter."id="ElementX" name="ElementX" value="" />
`
```
// Bootstrap was set with v.debounce = 0;

// On a button click, check if empty field is valid.
let isValid = v.isFieldValid(element));

// Returns true

```

Thank you

Ryan

### PR DESCRIPTION
**Pull request by dahlbyk**
- Fixes #100
  - cc #107
- Fixes #108 

More than I usually like to change at once, but all interrelated. In particular:
- Fixes some bugs related to removing validation from a field/form
- Removing validation from a field/form now also unwires event handlers
- Validation is now only debounced on input/change; manual validation calls start (and resolve, if none are async) immediately
- `validateForm()` and `validateField()` have been changed from returning `void` to returning `Promise<boolean>`, resolving with the same value their `callback` would receive.

### CODE REVIEW

**Comment by haacked** [comment]
I've started reviewing this.

File: src/index.ts [hunk 1]
```diff
@@ -1011,12 +1023,20 @@ export class ValidationService {
 
     private untrackFormInput(form: HTMLFormElement, inputUID: string) {
         let formUID = this.getElementUID(form);
-        if (!this.formInputs[formUID]) {
+        let formInputs = this.formInputs[formUID]
+        if (!formInputs) {
             return;
         }
         let indexToRemove = this.formInputs[formUID].indexOf(inputUID);
```
Comment (haacked) [inline src/index.ts:1030]: Since the new code sets `formInputs` to `this.formInputs[formUID]`, this could be changed to:

```suggestion
        let indexToRemove = formInputs.indexOf(inputUID);
```

File: src/index.ts [hunk 2]
```diff
@@ -1011,12 +1023,20 @@ export class ValidationService {
...
         if (indexToRemove >= 0) {
-            this.formInputs[formUID].splice(indexToRemove, 1);
+            formInputs[formUID].splice(indexToRemove, 1);
```
Comment (haacked) [inline src/index.ts:1032]: It looks like this should have been changed to:

```suggestion
            formInputs.splice(indexToRemove, 1);
```

Because `formInputs` was set to `this.formInputs[formUID]` and the previous code had this set to `this.formInputs[formUID].splice(indexToRemove, 1);`

File: src/index.ts [hunk 3]
```diff
@@ -1011,12 +1023,20 @@ export class ValidationService {
 
     private untrackFormInput(form: HTMLFormElement, inputUID: string) {
         let formUID = this.getElementUID(form);
-        if (!this.formInputs[formUID]) {
+        let formInputs = this.formInputs[formUID]
```
Comment (haacked) [inline src/index.ts:1026]: I think this is a little confusing (as evidenced by the bug I point out later). As I understand it, `this.formInputs` is a way of looking up all form inputs for a form. And `formInputs` is all the inputs for the current form. So we may want to rename this local variable something like `currentFormInputs`.

And for extra credit, perhaps `this.formInputs` should be `this.formsInputs` or `this.forms`?

**Review by haacked — CHANGES_REQUESTED** [review]
Found a bug during my testing. It's in the review.

File: src/index.ts (hunk 3 above)
Comment (dahlbyk) [reply src/index.ts]: For now I've applied consistency in usage/naming (`formInputUIDs = this.formInputs[formUID]`), which (combined with your "use the variable" suggestion) makes the bug more obvious.

A more precise rename (`inputsByFormUID`?) might be useful, but there are several similar lookup fields we'd want to update for consistency.

File: src/index.ts (hunk 2 above)
Comment (dahlbyk) [reply src/index.ts]: Good catch!

**Review by haacked — APPROVED** [review]
Nice work!

Might be nice to include an example of how to clear existing validation messages when you disable validation. But that can happen later.

**Comment by haacked** [comment]
@lonix1 Great questions! Would you mind opening a new issue with these questions? New questions on a closed PR are easy to overlook. 😄
