### PR TITLE
Fix unintended submissions in Firefox caused by undefined value

### LINKED ISSUE #78: Calling `validateForm` submits the form in Firefox
I have a wizard style form with multiple sections where I call `validateForm` before the user tries to move to the next section. In Chrome this works as desired, but in Firefox it submits the form instead making it impossible to move beyond the first section.

Starting from `formValidationEvent` which is really `cb` the value `undefined` is passed for the `SubmitEvent` which causes it to bypass the call to `preValidate` which has a comment indicating that it is meant to prevent submission. The flow then progresses from `handleValidated` to `submitValidForm`. In Chrome it seems like the submission is actually prevented by accident; the line `var submitter = submitEvent.submitter;` throws an exception due to `submitEvent` being `undefined`. Firefox never gets past the call to `form.dispatchEvent(newEvent)` at which point it submits the form.

### PR DESCRIPTION
**Pull request by LiteracyFanatic**
Fixes #78

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -860,7 +860,9 @@ export class ValidationService {
 
                 // Firefox fix: redispatch 'submit' after finished handling this event
                 await new Promise(resolve => setTimeout(resolve, 0));
-                this.handleValidated(form, success, e);
+                if (e) {
+                    this.handleValidated(form, success, e);
```
Comment (dahlbyk) [inline src/index.ts:864]: I _think_ it makes more sense to pass `e` through here and ignore it in `handleValidated`, e.g.

```ts
    handleValidated = (form: HTMLFormElement, success: boolean, submitEvent?: SubmitEvent) => {
        if (success) {
            if (submitEvent) {
                this.submitValidForm(form, submitEvent);
            }
        }
        else {
            this.focusFirstInvalid(form);
        }
    }
```

That's a pretty small/straightforward method to override if someone needs different behavior for whatever reason.

Note I also adjusted `submitEvent?: SubmitEvent`. If we know we might pass around an `undefined` we should model that explicitly.

Comment (dahlbyk) [reply src/index.ts:864]: In retrospect it probably makes more sense to have `preValidate(form: HTMLFormElement, submitEvent?: SubmitEvent)`, with the missing event handled there instead of inside the form callback. That's technically a breaking change for anyone who's overriding `preValidate()`, but that may have just been me? (cc #33)

Comment (LiteracyFanatic) [reply src/index.ts]: Yeah, moving the check inside `handleValidated` is definitely better. The way I did it would prevent `focusFirstInvalid` from getting called even though it doesn't depend on the `submitEvent`.

**Review by dahlbyk — APPROVED** [review]
LGTM

**Review by haacked — APPROVED** [review]
:shipit:
