### PR TITLE
Fix Firefox post-validation `submit` handling

### LINKED ISSUE #61: Form e.preventDefault() broken in Firefox (0.8.3-0.8.13)
Hi there,

It seems any code such as the following in Firefox breaks.
Chrome / Edge seem ok, but Firefox doesn't work

`document.getElementById('my-form').addEventListener('submit', function (e) {        
        e.preventDefault();        
        alert('This doesn't get called because the page navigates away');
});
`
The page just navigates away without being stopped

I tried various versions of the library and v0.8.1 is the last working version 
**0.8.3-0.8.13 BROKEN**

@dahlbyk I noticed you made some changes during 0.8.3 release anything you can think of that would stop it form working in Firefox?

I suspect an issue with this part of the code
https://github.com/haacked/aspnet-client-validation/compare/v0.8.1...v0.8.3#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R728
       
image

Any help would be much appreciated

### PR DESCRIPTION
**Pull request by dahlbyk**
- Adds an `npm run build` before DemoWeb copies `dist/`
- Enables console logging for DemoWeb
- Fixes #61 
  - Form 4 in DemoWeb now includes a `preventDefault()` that reproduces the issue

From https://github.com/haacked/aspnet-client-validation/issues/61#issuecomment-1656586818:

> Apparently https://github.com/haacked/aspnet-client-validation/pull/33 just doesn't work on Firefox. Here's a minimal repro and a proposed fix: https://codepen.io/dahlbyk/full/oNQQoMq.
> 
> image
> 
> In short, Firefox isn't firing `submit` listeners for the redispatch here:
> https://github.com/haacked/aspnet-client-validation/blob/f09bb578574c129b07e06e4781fc47c0052314d3/src/index.ts#L718-L720
> 
> Using `setTimeout(fn, 0)` seems to allow the original `submit` handler to finish before dispatching at the next opportunity.
>

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -859,10 +859,16 @@ export class ValidationService {
                     });
                 form.dispatchEvent(validationEvent);
 
-                this.handleValidated(form, success, e);
+                // Firefox fix: redispatch 'submit' after finished handling this event
+                setTimeout(() => {
+                    try {
+                        this.handleValidated(form, success, e);
+                    } finally {
+                        validating = false;
```
Comment (dahlbyk) [inline src/index.ts:867]: I'm not thrilled with this being pulled out of the `finally()`. Might try promisifying the `setTimeout()`.

**Review by haacked — APPROVED** [review]
:shipit: Thanks!
