### PR TITLE
Ability to specify custom highlight / unhighlight functions

### LINKED ISSUE #38: Consider adding highlight/unhighlight events
I would love to replace our jQuery ASP.NET validation with this, but I can't because it's lacking the [highlight](https://jqueryvalidation.org/validate/#highlight) and [unhighlight](https://jqueryvalidation.org/validate/#unhighlight) events that we rely upon.

They're part of jQuery Validation rather than Microsoft's jQuery Unobtrusive Validation, and they let you run extra code at the time a field becomes valid or invalid. 

Our use case for this is that we need error messages to be replicated in an [Error summary](https://design-system.service.gov.uk/components/error-summary/) similar to ASP.NET validation summary as well as next to the field, and we need to prepend "Error: " to the page title when there is an error. These changes make error messages more accessible to assistive technology users.

Would you consider adding support for them?

### PR DESCRIPTION
**Pull request by xsustek**
Adds ability to specify custom highlight / unhighlight functions, defaults to original behavior and just swaps classes.

Fixes https://github.com/haacked/aspnet-client-validation/issues/38

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1513,6 +1513,26 @@ export class ValidationService {
...
+     */
+    highlight(input : ValidatableElement, errorClass: string, validClass: string) {
+        this.swapClasses(input, errorClass, validClass);
+    }
+
+    /**
+     * Unhighlight valid element by removing errorClass CSS class and adding validClass CSS class
+     * @param input Element to modify
+     * @param errorClass Class to add
+     * @param validClass Class to remove
```
Comment (dahlbyk) [inline src/index.ts:1530]:
```suggestion
     * @param errorClass Class to remove
     * @param validClass Class to add
```

**Review by dahlbyk — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by xsustek** [comment]
Hi @dahlbyk, is there anything else missing or that needs to be addressed before this can be merged? Thanks.

**Comment by dahlbyk** [comment]
> is there anything else missing or that needs to be addressed before this can be merged?

Nothing missing. @haacked cuts releases, but you could help him out by bumping package version to `0.11.1` and committing the result of `npm run build`.

**Comment by xsustek** [comment]
> > is there anything else missing or that needs to be addressed before this can be merged?
> 
> Nothing missing. @haacked cuts releases, but you could help him out by bumping package version to `0.11.1` and committing the result of `npm run build`.

Done

**Comment by haacked** [comment]
Sorry for the delay! Started a new job and have been pretty busy. :smile:

**Comment by haacked** [comment]
It's live on NPM! https://www.npmjs.com/package/aspnet-client-validation
